config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "/books", to: "books#index"
  # post "/books", to: "books#create"
  # get "/books/new", to: "books#new", as: "new_book"
  # get "/books/:id/edit", to: "books#edit", as: "edit_book"
  # get "/books/:id", to: "books#show", as: "book"
  # patch "/books/:id", to: "books#update"
  # delete "/books/:id", to: "books#destroy"

  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  validates :year, presence: true
  validates :month, presence: true
  validates :inout, presence: true
  validates :category, presence: true
  validates :amount, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
    @books = @books.where(year: params[:year]) if params[:year].present?
    @books = @books.where(month: params[:month]) if params[:month].present?
  end

  def show
  end

  def new
    nowDate = Time.new
    @book = Book.new
    @book.year = nowDate.year
    @book.month = nowDate.mon
  end

  def create
    @book = Book.new(book_param)
    if @book.save
      flash[:notice] = "家計簿に#{@book.year}年#{@book.month}月・#{@book.category}を登録しました。"
      redirect_to books_path
    else
      flash.now[:alert] = "登録に失敗しました。"
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_param)
      flash[:notice] = "#{@book.year}年#{@book.month}月・#{@book.category}を更新しました。"
      redirect_to edit_book_path
    else
      flash.now[:alert] = "更新に失敗しました。"
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:notice] = "削除しました"
    redirect_to books_path
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_param
    params.require(:book).permit(:year, :month, :inout, :category, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<h1>家計簿<%= type %></h1>
<%= form_with model: book, local: true, method: method do |f| %>
  <div class="from-group">
    <label>年度</label>
    <%= f.number_field :year, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>月</label>
    <%= f.number_field :month, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>区分</label>
    <%= f.select :inout, [["収入",1],["支出",2]], {}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <label>科目</label>
    <%= f.text_field :category, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>金額</label>
    <%= f.number_field :amount, class: "form-control"%>
  </div>
  <%= link_to "戻る", books_path, class: "btn btn-secondary" %>
  <%= f.submit type, class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<%= render partial: "form", locals: { type: "更新", book: @book, method: "patch" } %>

app/views/books/index.html.erb
<h1>家計簿</h1>
<div class="card">
  <div class="card-body">
    <%= form_with method: "get", local: true do |f| %>
      <div class="form-row">
        <div class="col">
          <%= f.number_field "year", placeholder: "年度を入力", class: "form-control" %>
        </div>
        <div class="col">
          <%= f.number_field "month", placeholder: "対象月を入力", class: "form-control" %>
        </div>
        <div class="col">
          <%= f.submit "検索", class: "btn btn-primary"%>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to "新規登録", new_book_path, class:" btn btn-primary" %>
<table class="table table-striped">
  <tr>
    <th>年月</th>
    <th>区分</th>
    <th>科目</th>
    <th>金額</th>
    <th>リンク</th>
  </tr>
  <% sum = 0 %>
  <% income = 0 %>
  <% expenditure= 0 %>
  <% inout = ""%>
  <% @books.each do | book| %>
    <%if book.inout == 1 %>
      <% inout = "収入" %>
    <% else %>
      <% inout = "支出"%>
    <% end %>
    <tr>
      <td><%= book.year %>年<%= book.month %>月</td>
      <td><%= inout %></td>
      <td><%= book.category %></td>
      <td><%= book.amount %>万円</td>
      <td>
        <%= link_to "詳細", book_path(book), class: "btn btn-info" %>
        <%= link_to "編集", edit_book_path(book), class: "btn btn-warning" %>
        <%= link_to "削除", book_path(book), data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete}, class: "btn btn-danger" %>
      </td>
    </tr>
    <% if book.inout == 1 %>
      <% sum += book.amount %>
      <% income += book.amount%>
    <% else %>
      <% sum -= book.amount %>
      <% expenditure += book.amount %>
    <%end%>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td>収入合計</td>
    <td><%= income %>万円</td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td>支出合計</td>
    <td><%= expenditure %>万円</td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td>収支</td>
    <td><%= sum %>万円</td>
    <td></td>
  </tr>
</table>

app/views/books/new.html.erb
<%= render partial: "form", locals: { type: "登録", book: @book, method: nil } %>

app/views/books/show.html.erb
<h1>家計簿詳細</h1>
<table class="table table-striped">
  <tr>
    <th>年月</th>
    <td><%= @book.year %>年<%= @book.month %>月</td>
  </tr>
  <tr>
    <th>区分</th>
    <td><%= @book.inout %></td>
  </tr>
  <tr>
    <th>科目</th>
    <td><%= @book.category %></td>
  </tr>
  <tr>
    <th>金額</th>
    <td><%= @book.amount %></td>
  </tr>
</table>
<%= link_to "戻る", books_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakeibo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger" role="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>